import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PublicLayout from "@/components/layout/PublicLayout";
import { SidebarProvider } from "@/context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = "admin";

	return (
		<html lang="en">
			<body className={inter.className}>
				<SidebarProvider>
					{user ? <PublicLayout>{children}</PublicLayout> : children}
				</SidebarProvider>
			</body>
		</html>
	);
}
